// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGbYC4FV2G6m8b_IQF1Q_tfnpi4ZO3kmc',
    appId: '1:756436909038:web:b3978d4d0af9c92f66ecff',
    messagingSenderId: '756436909038',
    projectId: 'bonus4-6f61a',
    authDomain: 'bonus4-6f61a.firebaseapp.com',
    databaseURL: 'https://bonus4-6f61a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bonus4-6f61a.firebasestorage.app',
    measurementId: 'G-867NBDN2HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmldmItVh_9N9QUam43AQApU-VdP5rB_s',
    appId: '1:756436909038:android:d9c9f55d6a786d4466ecff',
    messagingSenderId: '756436909038',
    projectId: 'bonus4-6f61a',
    databaseURL: 'https://bonus4-6f61a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bonus4-6f61a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9y0XLigFlcIZZNbYh9NziR02_okpdFgM',
    appId: '1:756436909038:ios:2e5c953eae9e8e8d66ecff',
    messagingSenderId: '756436909038',
    projectId: 'bonus4-6f61a',
    databaseURL: 'https://bonus4-6f61a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bonus4-6f61a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
